import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learningSidebar: [
    'intro',
    {
      type: 'category',
      label: '课程路线',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'course'}],
    },
    {
      type: 'category',
      label: '原理知识',
      items: [{type: 'autogenerated', dirName: 'knowledge'}],
    },
    {
      type: 'category',
      label: '故障实验',
      items: [{type: 'autogenerated', dirName: 'labs'}],
    },
    {
      type: 'category',
      label: '架构与决策',
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
        {type: 'autogenerated', dirName: 'decisions'},
      ],
    },
    'glossary',
  ],
};

export default sidebars;
